---
ID: "82f1bca9-16be-4be6-9c93-1f46b9d59318"
Parent: "c72089dd-0991-4f32-805e-4c06531ebfb3"
Template: "c72089dd-0991-4f32-805e-4c06531ebfb3"
Path: /sitecore/templates/Feature/Products/Product Repository/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170513T081754Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
