---
ID: "e002c7a4-b38b-461a-81c1-9203e5dd6574"
Parent: "d8b04ccc-70a6-45a6-96b2-dd2c756f315c"
Template: "58119a3e-560e-4da6-97c6-1ace8a5b1219"
Path: /sitecore/system/Tasks/Commands/Habitat/Products/Products Importer
DB: master
SharedFields:
- ID: "4bc75539-d5c4-487b-af35-ff13d62bd286"
  Hint: Method
  Value: Execute
- ID: "752579a7-ef2f-45b7-b9d1-9b682308b7a5"
  Hint: Type
  Value: Sitecore.Feature.Products.Tasks.ProductImporter, Sitecore.Feature.Products
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20150811T125103Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
