---
ID: "c93fef07-386d-43f0-8767-07e19c30b553"
Parent: "6abd63aa-668e-4479-91cd-9037448cd754"
Template: "6abd63aa-668e-4479-91cd-9037448cd754"
Path: /sitecore/templates/Feature/Products/Product/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170513T081434Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
